name: skyradio_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.woff2
          weight: 100
        - asset: fonts/Poppins-ExtraLight.woff2
          weight: 200
        - asset: fonts/Poppins-Light.woff2
          weight: 300
        - asset: fonts/Poppins-Regular.woff2
          weight: 400
        - asset: fonts/Poppins-Medium.woff2
          weight: 500
        - asset: fonts/Poppins-SemiBold.woff2
          weight: 600
        - asset: fonts/Poppins-Bold.woff2
          weight: 700
        - asset: fonts/Poppins-ExtraBold.woff2
          weight: 800
        - asset: fonts/Poppins-Black.woff2
          weight: 900
        - asset: fonts/Poppins-Italic.woff2
          style: italic